### PR TITLE
french translations completed

### PR DESCRIPTION
**Pull request by K13b3r**

### CODE REVIEW

**Comment by stefanw** [comment]
The build failure indicates broken YAML. Check for apostrophes in bad places, bad quoting etc.

**Comment by K13b3r** [comment]
Ok but i don't know how to add words containings ' like "d'après vous?"
But I can do it really quickly I know where are the mistakes.

**Comment by K13b3r** [comment]
Without breaking the code

**Comment by stefanw** [comment]
Exactly like that: "d'après vous?" . The whole line needs to be quoted.

**Comment by K13b3r** [comment]
It must be good.

**Pull request merged**
