### PR TITLE
some fixes to polish translation + FNP guide to questions (includes HTML...

### PR DESCRIPTION
**Pull request by marcinkoziej**
..., beware)

### CODE REVIEW

**Comment by stefanw** [comment]
Thanks, could you merge in `okfde/gh-pages`? Don't forget to add your guide to `answers.yml`!

**Comment by marcinkoziej** [comment]
On 14.01.2014 15:28, Stefan Wehrmeyer wrote:

> Thanks, could you merge in |okfde/gh-pages|? Don't forget to add your
> guide to |answers.yml|!

Oh! i forgot. pushed it now. i will also merge later!

BR

## 

m.

**Comment by stefanw** [comment]
I wrote a Python script to merge in translations when conflict is too bad. It's in `scripts/merge_translations.py` and should be used like this:

```
pip install pyyaml
python merge_translations.py upstream_questions.yml your_newlanguage.yml language_code
python merge_translation.py ../_data/questions.yml questions_pl.yml pl > new_questions.yml
```

It will overwrite all `text` and `options.details` language options with the new version and print to stdout.

**Comment by stefanw** [comment]
Let me know if I should merge the branch with scripts.

**Comment by marcinkoziej** [comment]
On 15.01.2014 12:19, Stefan Wehrmeyer wrote:

> Let me know if I should merge the branch with scripts.
> If that's not a problem, please do!

## 

m.

GPG: E805 94F8 2A73 C019 DC1E  DA42 F7CE 8135 FAF1 678C

**Pull request merged**
